"""Protocol interfaces for dependency injection in tests."""
from __future__ import annotations

from pathlib import Path
from typing import Protocol, runtime_checkable

from models.feature import Feature


@runtime_checkable
class IFeatureManager(Protocol):
    def start_feature(self, project_dir: Path, name: str, subdir: str | None = None) -> Feature: ...
    def resume_feature(self, project_dir: Path, name: str) -> Feature | None: ...
    def complete_feature(self, project_dir: Path, name: str | None = None, session_id: str | None = None) -> Feature | None: ...
    def get_current_feature(self, project_dir: Path, session_id: str | None = None) -> Feature | None: ...
    def list_features(self, project_dir: Path) -> list[Feature]: ...
    def accumulate_tokens(self, project_dir: Path, input_tokens: int, output_tokens: int, cost_usd: float, feature_name: str | None = None) -> dict: ...
    def auto_complete_active_features(self, project_dir: Path, exclude_name: str | None = None) -> list[Feature]: ...
    def discard_feature(self, project_dir: Path, name: str) -> Feature | None: ...
    def register_cli_session(self, project_dir: Path, cli_session_id: str, feature_name: str) -> Feature | None: ...


@runtime_checkable
class IProjectManager(Protocol):
    def get_project_by_thread(self, thread_id: int) -> object | None: ...
    def get_project_dir(self, project: object) -> Path: ...


@runtime_checkable
class IClaudeRunner(Protocol):
    def is_busy(self, thread_id: int) -> bool: ...
    def cancel(self, thread_id: int) -> bool: ...
    def get_active_info(self, thread_id: int) -> tuple[str, float] | None: ...


@runtime_checkable
class IVoiceNotifier(Protocol):
    async def voice_event(self, guild: object, event_type: str, message: str) -> None: ...
